### ISSUE TITLE
java.sql.Date to Timestamp Conversion error

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rdbms#102]
When retrieving a date field from RDBMS entity, the following error occurs

2015-01-26 15:54:16,005 [hystrix-FindCommand-9] ERROR [com.redhat.lightblue.util.Error] java.util.Date cannot be cast to java.sql.Date: java.lang.ClassCastException: java.util.Date cannot be cast to java.sql.Date
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.processDynVar(RDBMSUtilsMetadata.java:176)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.getStatement(RDBMSUtilsMetadata.java:124)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.buildAllMappedList(RDBMSUtilsMetadata.java:219)
	at com.redhat.lightblue.hystrix.rdbms.ExecuteSQLCommand.run(ExecuteSQLCommand.java:74)
	at com.redhat.lightblue.hystrix.rdbms.ExecuteSQLCommand.run(ExecuteSQLCommand.java:31)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:355)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:350)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:419)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:405)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker$1.run(HystrixContextScheduler.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by derek63** [comment]
We also need to write some tests for this class, as it is currently at 0% coverage http://sonar.lightblue.io/drilldown/measures/2958?metric=coverage&rids%5B%5D=2976#
