### ISSUE TITLE
RDBMS can't handle/convert BigDecimal

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rdbms#103]
2015-01-26 16:18:30,425 [hystrix-FindCommand-9] ERROR [com.redhat.lightblue.util.Error] No enum constant com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.Classes.BigDecimal: java.lang.IllegalArgumentException: No enum constant com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.Classes.BigDecimal
	at java.lang.Enum.valueOf(Enum.java:236)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata$Classes.valueOf(RDBMSUtilsMetadata.java:140)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.processDynVar(RDBMSUtilsMetadata.java:155)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.getStatement(RDBMSUtilsMetadata.java:124)
	at com.redhat.lightblue.metadata.rdbms.converter.RDBMSUtilsMetadata.buildAllMappedList(RDBMSUtilsMetadata.java:219)
	at com.redhat.lightblue.hystrix.rdbms.ExecuteSQLCommand.run(ExecuteSQLCommand.java:74)
	at com.redhat.lightblue.hystrix.rdbms.ExecuteSQLCommand.run(ExecuteSQLCommand.java:31)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:355)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:350)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:419)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:405)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker$1.run(HystrixContextScheduler.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by derek63** [comment]
This happens when specifying a column that is some number type in the projection

**Comment by bserdar** [comment]
This is probably related to the ticket i opened related to types not being
used at all in rdbms
